volumes:
  db:
  storage:

services:

  subsarr:
    # image: ghcr.io/slimcdk/subsarr:dev
    build: .
    ports:
      - 8091:8090
    environment:
      SUBSARR_DB_DRIVER: sqlite
      SUBSARR_DB_DSN: /app/db/subsarr.db
      SUBSARR_STORAGE_BACKEND: filesystem
      SUBSARR_STORAGE_PATH: /app/storage
    volumes:
      - db:/app/db
      - storage:/app/storage
      - ./subscene-dump:/tmp/subscene-archive
    restart: unless-stopped
