// Code generated by sqlc. DO NOT EDIT.

package pgdb

import "database/sql"

type Subtitle struct {
	ID         string
	SubsceneID string
	Title      string
	Slug       string
	ImdbID     string
	Language   string
	Hi         bool
	Author     string
	Releases   []byte // JSONB
	Comment    string
	Year       int32
	Filename   string
	Format     string
	ContentKey string
	UploadedAt sql.NullTime
	Downloads  int32
}

type ListLanguagesRow struct {
	Language string
	Count    int64
}
