// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Subtitle struct {
	ID          string
	SubsceneID  string
	Title       string
	Slug        string
	ImdbID      string
	Language    string
	Hi          bool
	Author      string
	Releases    json.RawMessage
	Comment     string
	Year        int32
	Filename    string
	Format      string
	ContentKey  string
	ContentHash string
	UploadedAt  sql.NullTime
	Downloads   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
