// Code generated by sqlc. DO NOT EDIT.

package pgdb

import (
	"context"
	"database/sql"
)

const getSubtitle = `-- name: GetSubtitle :one
SELECT id, subscene_id, title, slug, imdb_id, language, hi, author, releases,
       comment, year, filename, format, content_key, uploaded_at, downloads
FROM subtitles WHERE id = $1
`

func (q *Queries) GetSubtitle(ctx context.Context, id string) (Subtitle, error) {
	row := q.db.QueryRowContext(ctx, getSubtitle, id)
	var i Subtitle
	err := row.Scan(
		&i.ID, &i.SubsceneID, &i.Title, &i.Slug, &i.ImdbID,
		&i.Language, &i.Hi, &i.Author, &i.Releases, &i.Comment,
		&i.Year, &i.Filename, &i.Format, &i.ContentKey, &i.UploadedAt,
		&i.Downloads,
	)
	return i, err
}

const insertSubtitle = `-- name: InsertSubtitle :execresult
INSERT INTO subtitles (
    id, subscene_id, title, slug, imdb_id, language, hi,
    author, releases, comment, year, filename, format,
    content_key, uploaded_at, downloads
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT (slug, subscene_id, filename) DO NOTHING
`

type InsertSubtitleParams struct {
	ID         string
	SubsceneID string
	Title      string
	Slug       string
	ImdbID     string
	Language   string
	Hi         bool
	Author     string
	Releases   []byte
	Comment    string
	Year       int32
	Filename   string
	Format     string
	ContentKey string
	UploadedAt sql.NullTime
	Downloads  int32
}

func (q *Queries) InsertSubtitle(ctx context.Context, arg InsertSubtitleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertSubtitle,
		arg.ID, arg.SubsceneID, arg.Title, arg.Slug, arg.ImdbID,
		arg.Language, arg.Hi, arg.Author, arg.Releases, arg.Comment,
		arg.Year, arg.Filename, arg.Format, arg.ContentKey, arg.UploadedAt,
		arg.Downloads,
	)
}

const incrementDownloads = `-- name: IncrementDownloads :exec
UPDATE subtitles SET downloads = downloads + 1 WHERE id = $1
`

func (q *Queries) IncrementDownloads(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementDownloads, id)
	return err
}

const listLanguages = `-- name: ListLanguages :many
SELECT language, COUNT(*) AS count
FROM subtitles
WHERE language != ''
GROUP BY language
ORDER BY count DESC
`

func (q *Queries) ListLanguages(ctx context.Context) ([]ListLanguagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLanguagesRow
	for rows.Next() {
		var i ListLanguagesRow
		if err := rows.Scan(&i.Language, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
