// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitedb

type Subtitle struct {
	ID          string
	SubsceneID  string
	Title       string
	Slug        string
	ImdbID      string
	Language    string
	Hi          int64
	Author      string
	Releases    string
	Comment     string
	Year        int64
	Filename    string
	Format      string
	ContentKey  string
	ContentHash string
	UploadedAt  string
	Downloads   int64
	CreatedAt   string
	UpdatedAt   string
}
