// Code generated by sqlc. DO NOT EDIT.

package sqlitedb

import (
	"context"
	"database/sql"
)

const getSubtitle = `-- name: GetSubtitle :one
SELECT id, subscene_id, title, slug, imdb_id, language, hi, author, releases,
       comment, year, filename, format, content_key, uploaded_at, downloads
FROM subtitles WHERE id = ?
`

func (q *Queries) GetSubtitle(ctx context.Context, id string) (Subtitle, error) {
	row := q.db.QueryRowContext(ctx, getSubtitle, id)
	var i Subtitle
	err := row.Scan(
		&i.ID, &i.SubsceneID, &i.Title, &i.Slug, &i.ImdbID,
		&i.Language, &i.Hi, &i.Author, &i.Releases, &i.Comment,
		&i.Year, &i.Filename, &i.Format, &i.ContentKey, &i.UploadedAt,
		&i.Downloads,
	)
	return i, err
}

const insertSubtitle = `-- name: InsertSubtitle :execresult
INSERT OR IGNORE INTO subtitles (
    id, subscene_id, title, slug, imdb_id, language, hi,
    author, releases, comment, year, filename, format,
    content_key, uploaded_at, downloads
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSubtitleParams struct {
	ID         string
	SubsceneID string
	Title      string
	Slug       string
	ImdbID     string
	Language   string
	Hi         int64
	Author     string
	Releases   string
	Comment    string
	Year       int64
	Filename   string
	Format     string
	ContentKey string
	UploadedAt string
	Downloads  int64
}

func (q *Queries) InsertSubtitle(ctx context.Context, arg InsertSubtitleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertSubtitle,
		arg.ID, arg.SubsceneID, arg.Title, arg.Slug, arg.ImdbID,
		arg.Language, arg.Hi, arg.Author, arg.Releases, arg.Comment,
		arg.Year, arg.Filename, arg.Format, arg.ContentKey, arg.UploadedAt,
		arg.Downloads,
	)
}

const incrementDownloads = `-- name: IncrementDownloads :exec
UPDATE subtitles SET downloads = downloads + 1 WHERE id = ?
`

func (q *Queries) IncrementDownloads(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementDownloads, id)
	return err
}

const listLanguages = `-- name: ListLanguages :many
SELECT language, COUNT(*) AS count
FROM subtitles
WHERE language != ''
GROUP BY language
ORDER BY count DESC
`

func (q *Queries) ListLanguages(ctx context.Context) ([]ListLanguagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLanguagesRow
	for rows.Next() {
		var i ListLanguagesRow
		if err := rows.Scan(&i.Language, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
